apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushworker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pushworker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: pushworker
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: WEBHOOK_URL
              value: http://webhook:5000
          image: localhost:5000/trivy_runner_pushworker:latest
          name: pushworker
      restartPolicy: Always
      volumes:
        - name: shared-reports-volume
          persistentVolumeClaim:
            claimName: shared-reports-claim
