version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - trivy-net

  webapi:
    build:
      context: .
      dockerfile: Dockerfile-webapi
    ports:
      - "8080:8080"
    networks:
      - trivy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-reports:/app/reports
    depends_on:
      - redis

  pullworker:
    build:
      context: .
      dockerfile: Dockerfile-pullworker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-reports:/app/reports
    networks:
      - trivy-net
    depends_on:
      - redis

  trivyscanner:
    build:
      context: .
      dockerfile: Dockerfile-trivyworker
    networks:
      - trivy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-reports:/app/reports
    depends_on:
      - redis


networks:
  trivy-net:
    driver: bridge

