version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - trivy-net

  webapi:
    build:
      context: .
      dockerfile: ./build/Dockerfile-webapi
    ports:
      - "8080:8080"
    networks:
      - trivy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-reports:/app/reports
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  pullworker:
    build:
      context: .
      dockerfile: ./build/Dockerfile-pullworker
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    networks:
      - trivy-net
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  pushworker:
    build:
      context: .
      dockerfile: Dockerfile-pushworker
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    networks:
      - trivy-net
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBHOOK_URL=http://catalog:3000/webhooks/trivy

  scanworker:
    build:
      context: .
      dockerfile: Dockerfile-scanworker
    networks:
      - trivy-net
    volumes:
      - ./images:/app/images
      - ./trivy-reports:/app/reports
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  trivy-net:
    driver: bridge

