apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushworker
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deploy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: pushworker
        image: "registry.opensuse.org/home/vpereirabr/dockerimages/containers/vpereirabr/trivy_runner_pushworker:latest"
        env:
        - name: WEBHOOK_URL
          value: "{{ .Values.pushworker.webhookUrl }}"
