apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}-redis
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "deploy.fullname" . }}-redis
  ports:
    - port: 6379
      targetPort: 6379
