apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanworker
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deploy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: scanworker
        image: "registry.opensuse.org/home/vpereirabr/dockerimages/containers/vpereirabr/trivy_runner_scanworker:latest"
        env:
        - name: PUSH_TO_CATALOG
          value: "{{ .Values.scanworker.pushToCatalog }}"
