name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20' # Use the version of Go in your project

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Makefile 'test' target
      run: make test

    - name: Run Makefile 'all' target
      run: make all

